### ISSUE TITLE
SegmFault in x86 Linux

### ISSUE THREAD

**Issue by zonyitoo** [zonyitoo/coio-rs#12]
Segmentation fault when running `tcp-echo-server` in the example.

Platform: Debian 8 x86

Ref: #10

**Comment by zonyitoo** [comment]
Bug confirmed. SegmFault happened while calling `mio::TcpListener::accept`. Unknown reason.

**Comment by szagi3891** [comment]
Problem in the create mio ?

**Comment by zonyitoo** [comment]
It seems no. I also tried to run the tests in MIO, and they all passed.

**Comment by szagi3891** [comment]
Maybe there are too much number of unsafe blocks in this create ?

**Comment by zonyitoo** [comment]
Most of them are just for manipulating the states of the `Coroutine` structs. I have found that

1. `examples/simple.rs` runs very well, so I think the context switch code is fine.
2. Once the coroutine is going to be blocked, the program crash. Such as `examples/timer.rs`.
3. Mio itself runs fine.

So the crash occurs when registering / after registered the event and going to block the coroutine.

**Comment by szagi3891** [comment]
if the create "coio-rs" is only supports mio as non-blocking operation ?
if i read file, then is non-blocking operation ?

**Comment by zonyitoo** [comment]
Yes it is. I have only supported MIO's async operations. Files are going to block right now.

I think most of the systems have read buffers for files. Supporting async file I/O may have to use `aio_*` APIs or a thread pool. I am still not sure how to support it well.

**Comment by zonyitoo** [comment]
Branch `feature-migrate_context1.0` still doesn't work in `Linux debian 3.16.0-4-586 #1 Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) i686 GNU/Linux`.

**Comment by zonyitoo** [comment]
Fixed. Going to close this issue.
