### ISSUE TITLE
Library hangs on Receiver::recv()

### ISSUE THREAD

**Issue by 3Hren** [zonyitoo/coio-rs#2]
Hi!

I have a library which internally uses `coio` dealing with TCP sockets. Look at the following abstract code:

```rust
coio::spawn(move || {
    // Here 2 coroutines spawns inside `new` function.
    // The first one listens TCP socket and redirects all data obtained into internal `tx`, the second coroutine waits for `rx` data from the previous `tx`.
    // After some preparations the data is transmitted into another `tx` which is connected with `rx` returned for User.
    let mut service = Service::new("locator".into(), ("::", 10053)).unwrap();

    // Here we obtain that `rx`.
    let (_, rx) = service.invoke(0, &["storage"]).unwrap();
    // This hangs forever, consuming all CPU.
    let (ty, _) = rx.recv().unwrap().unwrap();

    assert_eq!(0, ty);
});

coio::run(1);
```

I cannot provide the minimal failing example at this moment, but maybe you can take a look to see what can invoke such behavior.

**Comment by zonyitoo** [comment]
Is the `Receiver` `coio::sync::mpsc::Receiver`?

Are you sure that the data has already been sent into the `tx`?

**Comment by 3Hren** [comment]
1. Yes, it is.
2. At the moment of calling recv in the common case the data hasn't been sent of course.

**Comment by zonyitoo** [comment]
Then `recv` should hangs forever, because the current coroutine is waiting for data from the `tx`.

The current coroutine spinning on the `recv` method, so that it consumes all CPU.

Hmm.. What's your expecting behavior?

**Comment by 3Hren** [comment]
I expect suspending the current execution context until the data is available.

Similar as a socketpair instead of Sender/Receiver pair.

**Comment by zonyitoo** [comment]
Since the `Sender/Receiver` is a lock-free queue, I should take a look at how to implement that.

Thanks for your suggestion.

**Comment by 3Hren** [comment]
Hmm, then we need some kind of condvar to be able to wake up other coroutine.

**Comment by zonyitoo** [comment]
Check the commit 11362198e7a412ed037ec0a223c4e957ad9fe249
