### ISSUE TITLE
Coroutines won't be destroyed if they are in channel's wait list

### ISSUE THREAD

**Issue by zonyitoo** [zonyitoo/coio-rs#28]
This will cause memory leaks because when the `Sender`, `Receiver` and `SyncSender` are going to be destroyed, the `Processor` may already dead.

Reproduce code:

```rust
extern crate coio;

use coio::Scheduler;
use coio::sync::mpsc;

fn main() {

    Scheduler::new().with_workers(1).run(|| {
        let (tx, mut rx) = mpsc::channel();

        for i in 0..100 {
            let (ltx, lrx) = mpsc::channel();
            let name = format!("Coroutine #{}", i);
            Scheduler::spawn(move|| {
                loop {
                    let value = match rx.recv() {
                        Ok(v) => v,
                        Err(..) => break,
                    };
                    println!("{} passing {:?}", name, value);
                    ltx.send(value).unwrap();
                }
            });

            rx = lrx;
        }

        for i in 0..10 {
            println!("Master gives out {}", i);
            tx.send(i).unwrap();
            let value = rx.recv().unwrap();
            println!("Master gets {}", value);
            assert_eq!(i, value);
        }
    }).unwrap();

}
```

And add `println` in `Coroutine::drop` like this

```rust
impl Drop for Coroutine {
    fn drop(&mut self) {
        println!("Dropping!!");
        /// ...
}
```

You may only see 2 "Dropping" print out on the screen. Because when the main function is finished, the main coroutine is going to be destroyed. But who prints the other "Dropping"? I don't know... But all I know is most of them haven't been destroyed properly.

**Comment by lhecker** [comment]
Didn't we want to avoid the need of waking up coroutines by unwinding it's stack in Coroutine::drop()?

**Comment by zonyitoo** [comment]
No one will trigger it. As you can see in the code, when the main_function is finished, only then `tx` and `rx` will be destroyed. BUT the channel (`Sender` or `Receiver`) won't tell the other end that it is going to be destroyed. So the coroutine is still waiting in the waiting list, and it also owns the `Sender` and `Receiver` so that they won't be destroyed.

**Comment by lhecker** [comment]
Ah... I missed the important bit: The coroutine owns the channel and the channel owns the coroutine... a cyclic dependency!

**Comment by zonyitoo** [comment]
Indeed. So that's why I add this commit. The `Sender` and `SyncSender`, `SyncReceiver` should wake up all the waiting coroutines.

**Comment by lhecker** [comment]
Yeah I know... As I said: The important bit is the cyclic dependency of "coroutine owns the channel and the channel owns the coroutine". We might want to add this in a comment in the code to prevent similiar errors later on...

**Comment by zonyitoo** [comment]
Alright.

**Comment by zonyitoo** [comment]
I recognized a bug. Because I am waking up coroutines in the `Drop` trait, so what would happen if the coroutine is already running and try to call `try_recv` again on the `Receiver`, but the actual underlying `Sender` is still alive?
