### ISSUE TITLE
High idle CPU usage

### ISSUE THREAD

**Issue by sp3d** [zonyitoo/coio-rs#41]
It seems coio is hard-coded to sleep at most 1ms at a time, based on line 376 of processor.rs:

`thread::park_timeout(Duration::from_millis(1));`

This results in much more CPU time being used than necessary, and kills battery life on mobile.

What, design-wise, is preventing threads from sleeping indefinitely until waking on an event that might give them work to do?

Edit: Upon further inspection, it seems this may be within the scope of PR #27.

**Comment by zonyitoo** [comment]
Indeed. We are working on #27 to improve this parking strategy. But currently I am busy with porting the latest context-rs to this crate, so this issue would be delayed.

If you are interest, you can create a PR for us. :)

**Comment by zonyitoo** [comment]
Close because of duplication.
