### ISSUE TITLE
Support for plain TLS (not HTTPS)

### ISSUE THREAD

**Issue by jedisct1** [zonyitoo/coio-rs#5]
I wish I could send a pull request instead of a request, but my attempt at coding it during a Rust meetup today miserably failed.

Would it be possible to wrap rust-openssl's `SslStream` so that coio could be used for TLS in addition to TCP?

That would be awesome.

**Comment by zonyitoo** [comment]
You could just wrap the `TcpStream` with `SslStream` manually. It should work.

**Comment by jedisct1** [comment]
Hi,

Unfortunately, wrapping `TcpStream` with `SslStream` is not enough.
From https://gist.github.com/jedisct1/31d754ec8ce125c9a69a :

```rust
let sslclient = SslStream::accept(&ctx, client).unwrap();
```

    error: the trait `std::sys::ext::io::AsRawFd` is not implemented for the type `&coio::net::tcp::TcpStream` [E0277]

**Comment by zonyitoo** [comment]
Ah... I see, I haven't implement the `AsRawFd` for `TcpStream`.

**Comment by zonyitoo** [comment]
You may try to use `SslStream::accept_generic` for now

**Comment by jedisct1** [comment]
Is a `BufReader` (as in https://gist.github.com/jedisct1/31d754ec8ce125c9a69a#file-x-rs-L22) usable within coio, or is it going to block?

**Comment by zonyitoo** [comment]
It should work.

**Comment by zonyitoo** [comment]
Please check this commit if it works

**Comment by jedisct1** [comment]
It compiles but doesn't work:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: StreamError(Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } })', src/libcore/result.rs:736
stack backtrace:
   1:        0x10b648db0 - sys::backtrace::tracing::imp::write::h825921edb3d1b1a5Y7s
   2:        0x10b647f13 - panicking::on_panic::h43e7f1d33c4a1811wWw
   3:        0x10b63df42 - sys_common::unwind::begin_unwind_inner::heb4e20796bd0bc86vas
   4:        0x10b63e46e - sys_common::unwind::begin_unwind_fmt::h78431852419d1eb0B9r
   5:        0x10b647797 - rust_begin_unwind
   6:        0x10b6678b0 - panicking::panic_fmt::hfe317d428639534enyH
   7:        0x10b5c69d5 - result::Result<T, E>::unwrap::h10304712157436955545
   8:        0x10b5c41a6 - main::closure.9895
   9:        0x10b5c3f2d - scheduler::Scheduler::spawn_opts::closure.9892
  10:        0x10b5c3af9 - thread::catch_panic::closure.9878
  11:        0x10b5c3aa9 - sys_common::unwind::try::try_fn::h16494376744086512690
  12:        0x10b6475d8 - __rust_try
  13:        0x10b645490 - sys_common::unwind::try::inner_try::he64433cb71e779f1T6r
  14:        0x10b5c3a13 - sys_common::unwind::try::h12912557507280480149
  15:        0x10b5c3827 - thread::catch_panic::h4071755150232364950
  16:        0x10b5c36ee - scheduler::Scheduler::spawn_opts::closure.9875
  17:        0x10b5c50d8 - boxed::F.FnBox<A>::call_box::h11328113379784261144
  18:        0x10b605b7b - boxed::Box<FnBox<A, Output $u3d$$u20$R$GT$$u2b$$u20$$u27$a$GT$.FnOnce$LT$A$GT$::call_once::h14704199642754790167
  19:        0x10b605a07 - coroutine::coroutine_initialize::__rust_abi
  20:        0x10b60599c - coroutine::coroutine_initialize::hff2d568379a4e95a7Dc
```

**Comment by zonyitoo** [comment]
Oh, well, don't call panic inside coroutines. Use

```rust
if let Err(err) = xxx {
    // Error occurs, logs it out and return
    return;
}
```

Because the latest Rust nightly have removed the `std::rt` mod, so it will definitely crash if you call `panic!` inside a coroutine. Check #6

**Comment by jedisct1** [comment]
Look at the code: https://gist.github.com/jedisct1/31d754ec8ce125c9a69a

I don't call `panic!()`. I think it's actually `SslStream::accept()` failing because the connection hasn't been established yet.

It works with `accept_generic()` though.

**Comment by zonyitoo** [comment]
`.unwrap()` will call `panic!` if it fails. I read the underlining code of `SslStream::accept`, it seems that it should finish the handshake before it return, or it will report an error.

You should use

```rust
let sslclient = match SslStream::accept(&ctx, client) {
    Ok(stream) => stream,
    Err(err) => {
        println!("Err: {:?}", err);
        return;
    }
};
```

to see what happened

**Comment by jedisct1** [comment]
I get the expected

    Err: StreamError(Error { repr: Os { code: 35, message: "Resource temporarily unavailable" } })

message, and then the connection is immediately closed. 
Should `accept()` be in a loop until it succeeds?

**Comment by zonyitoo** [comment]
Ah... `SSL_ERROR_WANT_READ` or `SSL_ERROR_WANT_WRITE` occurs.

It seems that openssl uses the raw fd to communicate. Which makes it bypassed the control of coio. So the solution is to use `accept_generic`.

**Comment by zonyitoo** [comment]
Close this because of lack of activities.
