### ISSUE TITLE
Consider adding a feature gate for `coio::net::http` ?

### ISSUE THREAD

**Issue by jedisct1** [zonyitoo/coio-rs#7]
`net::http` is neat, but requires Hyper, which itself requires quite a few dependencies.

These dependencies are obviously pulled even for apps that don't use `net::http`.

They also make it difficult to use coio with a different version of these dependencies.

Would you possibly consider requiring a feature to compile `net::http`?

**Comment by zonyitoo** [comment]
Hmm, indeed. Actually I just add the `net::http` for benching.

Currently the `net::http` is based on some codes copied from an old version of Hyper, I think it just could be removed.

Let me do this.

**Comment by zonyitoo** [comment]
Done. e2f6912c9cab18722314c0a4d5d854cf5eeb2c9d

**Comment by jedisct1** [comment]
Awesome, thanks!
